# Generated by Django 4.2.7 on 2025-04-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_collaborators'),
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tasks.task'),
            preserve_default=False,
        ),
    ]
