# Generated by Django 4.2.7 on 2025-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_docs_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='onedrive_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
