# Generated by Django 4.2.7 on 2025-04-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0003_docs_onedrive_link_alter_docs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
